#!/bin/sh

alias gp='git push'
alias gpf='git push --force'
alias gs='clear && git status'
alias gch='git checkout'
alias gc='git commit'
alias gca='git commit --amend --no-edit'
alias ga='git add'
alias gd='git diff'
alias gl='git log'
alias gpu='git pull'
alias gm='$EDITOR $(git ls-files -m --exclude-standard --others)'

alias v='$EDITOR'
alias g='git'
alias n='cd ~/notes && $EDITOR .'
alias mh='neomutt -F ~/.config/mutt/account.home && exit'
alias mw='neomutt -F ~/.config/mutt/account.work && exit'
alias nb='offlinerss && newsboat && offlinerss'
alias nr='sudo systemctl restart iwd'

alias zshrc='$EDITOR ~/.zshrc'
alias vimrc='$EDITOR ~/.vimrc'
alias wmconf='$EDITOR ~/.config/sway/config'
alias tconf='$EDITOR ~/.config/alacritty/alacritty.yml'
alias fconf='$EDITOR ~/.config/lf/lfrc'
alias rssconf='$EDITOR ~/.config/newsboat/config'
alias mconf='$EDITOR ~/.config/mutt/muttrc'
alias al='$EDITOR ~/.config/aliases'

alias mpvc='mpv --really-quiet $(wl-paste) & disown && exit'
alias f='fzf --bind "enter:execute(vim {})+abort"'
alias ytdl='youtube-dl'
alias pi='ping 1.1.1.1'
alias eip='curl icanhazip.com'
alias up='sudo dnf up && flatpak upgrade'
alias fwu='sudo fwupdmgr refresh; sudo fwupdmgr get-updates && sudo fwupdmgr update'

alias tetris='autoload -Uz tetriscurses; tetriscurses'
alias bc='bc -q -l'
alias tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
alias mpv='setsid mpv'

# Get length of string
alias lc='expr length'

# RetroArch
alias genesis='retroarch -L /usr/lib/libretro/genesis_plus_gx_libretro.so'
alias tg16='retroarch -L /usr/lib/libretro/mednafen_pce_libretro.so'

iso2device() {
  # Usage: iso2device ubuntu-18.04.1-desktop-amd64.iso /dev/sda
  du -h $1 && \
  sudo dd bs=4M if=$1 of=$2 status=progress oflag=sync
}

kupong() {
  curl -s "https://www.clearon.se/wp-admin/admin-ajax.php" --data-raw "action=CallAPI&eanCode=$1" | python -mjson.tool
}
