#!/bin/sh

alias gp='git commit -am "`date`" && git push'
alias gs='clear && git status'
alias m='make'
alias mcl='make clean'
alias gch='git checkout'
alias gc='git commit'
alias gd='git diff'
alias gpu='git pull'
alias gm='$EDITOR -p $(git ls-files -m --exclude-standard --others)'

alias v='$EDITOR'
alias g='git'
alias mh='neomutt -F ~/.config/mutt/account.home && exit'
alias mw='neomutt -F ~/.config/mutt/account.work && exit'
alias nb='newsboat'
alias nr='sudo systemctl restart NetworkManager'

alias bashrc='$EDITOR ~/.bashrc'
alias vimrc='$EDITOR ~/.vimrc'
alias wmconf='$EDITOR ~/.config/sway/config'
alias tconf='$EDITOR ~/.config/alacritty/alacritty.yml'
alias rssconf='$EDITOR ~/.config/newsboat/config'
alias mconf='$EDITOR ~/.config/mutt/muttrc'
alias al='$EDITOR ~/.config/aliases'

alias mpvc='mpv --really-quiet $(wl-paste) & disown && exit'
alias unp='unp -U'
alias f='fzf --bind "enter:execute(vim {})+abort"'
alias ytdl='youtube-dl -f "bestvideo[height <= 1080]+bestaudio/best" --write-sub --write-auto-sub --embed-subs -o "/home/david/youtube/%(uploader)s/%(upload_date)s-%(title)s-%(id)s.%(ext)s"'
alias pi='ping 1.1.1.1'
alias eip='curl icanhazip.com'
alias scli='scli --save-history'
alias ct='ctags -R'
alias fwu='sudo fwupdmgr refresh && sudo fwupdmgr get-updates && sudo fwupdmgr update'

#iso2device() {
  # Usage: iso2device ubuntu-18.04.1-desktop-amd64.iso /dev/sda
  # sudo dd bs=4M if=$1 of=$2 status=progress oflag=sync
#}

#yt() {
#  a="${1%.*}"
#  xdg-open https://invidio.us/watch?v="${a: -11}"
#}
